name: Simple Build ID Tagging

on:
  push:
    branches:
      - main # Triggers on pushes to the 'main' branch
    paths-ignore:
      - 'README.md' # This line prevents the workflow from running if only the README.md file is changed


jobs:
  tag-and-env:
    runs-on: ubuntu-latest # The environment where the job runs

    # Required permission to push tags back to your repository
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Gets your repository's code
        with:
          fetch-depth: 0 # Essential for Git tagging operations

      - name: Set APP_RUN_ID environment variable
        # This line makes the GitHub Actions run_id available as 'APP_RUN_ID'
        # for subsequent steps in this job and for your Next.js build (server-side).
        run: echo "APP_RUN_ID=${{ github.run_id }}" >> $GITHUB_ENV

      - name: Configure Git user
        # Git requires a user name and email to create tags
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push Git tag
        # Creates an annotated tag named 'run-<run_id>' on the current commit
        # and pushes it to your GitHub repository.
        run: |
          TAG_NAME="run-${{ github.run_id }}"
          git tag -a $TAG_NAME -m "Build tag for run ID: ${{ github.run_id }}"
          git push origin $TAG_NAME
